name: This is my first workflow

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

jobs:
  job1:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo This is my job1 workflow,
        echo test, and deploy your project.

    - name: Run a single-line script
      run: |
       echo Hello This  is my second workflow,
       echo test, and deploy your project.

  job2 : 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo This is my job2 workflow,
        echo test, and deploy your project.

  job3 : 
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        echo This is my job3 workflow,
        echo test, and deploy your project.